#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'hola_types'

module HolaServicio
  class Client
    include ::Thrift::Client

    def hola_func()
      send_hola_func()
      return recv_hola_func()
    end

    def send_hola_func()
      send_message('hola_func', Hola_func_args)
    end

    def recv_hola_func()
      result = receive_message(Hola_func_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'hola_func failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_hola_func(seqid, iprot, oprot)
      args = read_args(iprot, Hola_func_args)
      result = Hola_func_result.new()
      result.success = @handler.hola_func()
      write_result(result, oprot, 'hola_func', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Hola_func_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Hola_func_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

